// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw7j3LseVG6OZhuLGA9GYRhULaEBqfQd0',
    appId: '1:168994635531:android:7e93212a1c65165f53ec0e',
    messagingSenderId: '168994635531',
    projectId: 'pomodorotimer-9381a',
    authDomain: 'pomodorotimer-9381a.firebaseapp.com',
    storageBucket: 'pomodorotimer-9381a.appspot.com',
    measurementId: 'G-LEGVHN59TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7j3LseVG6OZhuLGA9GYRhULaEBqfQd0',
    appId: '1:168994635531:android:7e93212a1c65165f53ec0e',
    messagingSenderId: '168994635531',
    projectId: 'pomodorotimer-9381a',
    storageBucket: 'pomodorotimer-9381a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7j3LseVG6OZhuLGA9GYRhULaEBqfQd0',
    appId: '1:168994635531:android:7e93212a1c65165f53ec0e',
    messagingSenderId: '168994635531',
    projectId: 'pomodorotimer-9381a',
    storageBucket: 'pomodorotimer-9381a.appspot.com',
    iosBundleId: 'com.creativepulse.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7j3LseVG6OZhuLGA9GYRhULaEBqfQd0',
    appId: '1:168994635531:android:7e93212a1c65165f53ec0e',
    messagingSenderId: '168994635531',
    projectId: 'pomodorotimer-9381a',
    storageBucket: 'pomodorotimer-9381a.appspot.com',
    iosBundleId: 'com.creativepulse.pomodoro.RunnerTests',
  );
}
